# Generated by Django 6.1.2 on 2026-10-09 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_book_description_member_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circulationrecord',
            options={'ordering': ['-request_date', '-id']},
        ),
        migrations.AddField(
            model_name='circulationrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Librarian or staff who approved or rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_circulations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circulationrecord',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Optional reason if request was rejected'),
        ),
        migrations.AddField(
            model_name='circulationrecord',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when borrowing was requested by student'),
        ),
        migrations.AddField(
            model_name='circulationrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved / Active Loan'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='APPROVED', help_text='Current state of borrowing request or loan', max_length=20),
        ),
        migrations.AlterField(
            model_name='circulationrecord',
            name='due_date',
            field=models.DateField(blank=True, help_text='14-day loan expiration date', null=True),
        ),
        migrations.AlterField(
            model_name='circulationrecord',
            name='issue_date',
            field=models.DateField(blank=True, help_text='Date approved and issued by librarian', null=True),
        ),
    ]
